language: node_js
matrix:
  include:
    - node_js: '0.10'
    - node_js: '0.12'
    - node_js: iojs
    - node_js: '4.0'
      env: COVERALLS=1
after_success:
  - '[[ "$COVERALLS" ]] && gulp coveralls'
